### ISSUE TITLE
New update 1.15.2 breaks the mod

### ISSUE THREAD

**Issue by kochchef** [Marechal-L/Dark-Souls-III-Archipelago-client#9]
Hi,

it seems like there is a new version 1.15.2 since 12. janurary 2023 which breaks your mod :(

**Comment by Arucied** [comment]
Can confirm, i had to rollback to 1.15 version to get it to work.

Now i'm not on a standard setup, i'm running this on linux proton (which i had to install Microsoft Visual C++ Redistributable into that wineprefix); but i assume you're running this on not-linux so that information probably doesn't matter.

**Comment by Marechal-L** [comment]
The version 3.0.0 of the mod will address this issue by working on the 1.15.2 version
